INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_MODER');
INSERT INTO roles (name) VALUES ('ROLE_YT');
INSERT INTO roles (name) VALUES ('ROLE_SERVICE');
